#!/bin/sh

# Linter çalıştır
echo "Running lint..."
npx turbo lint

# Formatter çalıştır
echo "Running formatter..."
npx prettier --write "**/*.{js,jsx,ts,tsx,json,md}"

# Formatting check
echo "Running formatting check..."
npx prettier --check "**/*.{js,jsx,ts,tsx,json,md}"

