#!/bin/sh

# Linter çalıştır
echo "Running lint..."
npm run lint

# Formatter çalıştır
echo "Running formatter..."
npm run format

# Formatting check
echo "Running formatting check..."
npm run format -- --check

